import React from "react";
import { gradientStyleToReactStyleObject } from "../utils";
import "./content.css";

export default function Content({ gradientStyles }) {
  return (
    <div className="content">
      <div
        className="gradient"
        style={
          gradientStyles
            ? gradientStyleToReactStyleObject(gradientStyles)
            : {
                background: `radial-gradient(ellipse at bottom, #9900EF, #2F95BC)`,
              }
        }
      ></div>
      <div className="info">
        <section className="about">
          <h2>About CSS Gradients</h2>
          <p>
            The CSS Gradient online generator tool is a nice and simple to use
            utility to quickly generate linear and radial color gradients. You
            can create the gradients and export the CSS code with colors in HEX
            or RGB format.
          </p>
          <p>
            Keep reading below to learn more about <span>Linear Gradients</span>
            , <span>Radial Gradients</span> or <span>Text Gradients</span>.
          </p>
          <p>
            Or, get inspired and discover more gradient backgrounds by color:{" "}
            <span>Red Gradient backgrounds</span>{" "}
            <span>Orange Gradient backgrounds</span>{" "}
            <span>Yellow Gradient backgrounds</span>{" "}
            <span>Green Gradient backgrounds</span>{" "}
            <span>Azure Gradient backgrounds</span>{" "}
            <span>Blue Gradient backgrounds</span>{" "}
            <span>Purple Gradient backgrounds</span>{" "}
            <span>Pink Gradient backgrounds</span> or{" "}
            <span>Monochrome Gradient backgrounds</span>
          </p>
        </section>
        <hr />
        <section className="whatIsACssGradient">
          <h2>WHAT IS A CSS GRADIENT?</h2>
          <p className="lb">
            CSS3 gradients let you display smooth transitions between two or
            more specified colors. Earlier, you had to use images for these
            effects. However, by using CSS3 gradients you can reduce download
            time and bandwidth usage. In addition, elements with gradients look
            better when zoomed, because the gradient is generated by the
            browser.
            <br />
            <br />
            CSS3 defines two types of gradients:
            <br />- <span>Linear Gradients</span> (direction
            down/up/left/right/diagonally)
            <br />- <span>Radial Gradients</span> (defined by their center)
            <br />
            <br />
            Definition from
            <a
              href="https://www.w3schools.com/csS/css3_gradients.asp"
              target="blank"
            >
              W3Schools
            </a>
          </p>

          <p className="lb">
            The &lt;gradient&gt; CSS data type denotes a CSS &lt;image&gt; made
            of a progressive transition between two or more colors. A CSS
            gradient is not a CSS &lt;color&gt; but an image with no intrinsic
            dimensions; that is, it has no natural or preferred size, nor a
            preferred ratio. Its concrete size will match the one of the element
            it applies to.
            <br />
            <br />
            There are three kinds of color gradients:
            <br />
            - linear gradients, generated by the linear-gradient() function,
            where the color smoothly fades along an imaginary line.
            <br />
            - radial gradients, generated by the radial-gradient() function. The
            more away from an origin a point is, the more far from the original
            color it is.
            <br />
            - repeating gradients, which are fixed sized linear or radial
            gradients repeated as much as needed to fill the entire box.
            <br />
            <br />
            Definition from{" "}
            <a
              href="https://developer.mozilla.org/en-US/docs/Web/CSS/gradient"
              target="blank"
            >
              MDN - Mozilla Developer Network
            </a>
          </p>
        </section>
        <hr />
        <section className="linearGradient">
          <h2>CSS LINEAR GRADIENT</h2>
          <h3>What is a CSS Linear Gradient?</h3>
          <p className="lb">
            A linear gradient is created by specifying a straight gradient line,
            and then several colors placed along that line. The image is
            constructed by creating an infinite canvas and painting it with
            lines perpendicular to the gradient line, with the color of the
            painted line being the color of the gradient line where the two
            intersect. This produces a smooth fade from each color to the next,
            progressing in the specified direction.
            <br />
            <br />
            Definition from{" "}
            <a
              href="https://drafts.csswg.org/css-images-3/#linear-gradients"
              target="blank"
            >
              W3C
            </a>
          </p>
          <p>
            Read more about how linear gradients works and how to generate them{" "}
            <a href="https://www.css-gradient.com/linear-gradients">here</a>{" "}
          </p>
        </section>
        <hr />
        <section className="radialGradients">
          <h2>CSS RADIAL GRADIENTS</h2>
          <h3>What is a CSS Radial Gradient</h3>
          <p className="lb">
            In a radial gradient, rather than colors smoothly fading from one
            side of the gradient box to the other as with linear gradients, they
            instead emerge from a single point and smoothly spread outward in a
            circular or elliptical shape.
            <br />
            A radial gradient is specified by indicating the center of the
            gradient (where the 0% ellipse will be) and the size and shape of
            the ending shape (the 100% ellipse). Color stops are given as a
            list, just as for linear-gradient(). Starting from the gradient
            center and progressing towards (and potentially beyond) the ending
            shape uniformly-scaled concentric ellipses are drawn and colored
            according to the specified color stops.
            <br />
            <br />
            Definition from{" "}
            <a
              href="https://drafts.csswg.org/css-images-3/#radial-gradients"
              target="blank"
            >
              W3C
            </a>
          </p>
          <p>
            {" "}
            Read more about how linear gradients works and how to generate them{" "}
            <a href="https://www.css-gradient.com/radial-gradients">
              here
            </a>{" "}
          </p>
        </section>
        <hr />
        <section className="cssTextGradients">
          <h2>CSS TEXT GRADIENTS</h2>
          <h3>What is a Text Gradient</h3>
          <div>
            Using gradient on a text works the same way as the linear gradient,
            only that in this case you apply the gradient to a text instead of
            filling a background.
            <br />
            You'll love it. Just try to hover over the website logo on the left
            and you'll see for yourself.
            <br /> Read more about how linear gradients works and how to
            generate them{" "}
            <a href="https://www.css-gradient.com/text-gradients">here</a>{" "}
          </div>
        </section>
        <hr></hr>
        <section className="moreAboutGradients">
          <h2> WHERE CAN I FIND MORE ABOUT GRADIENTS</h2>
          <div>
            You can find more informaiton about CSS gradient at{" "}
            <a
              href="https://www.w3schools.com/csS/css3_gradients.asp"
              target="blank"
            >
              W3Schools
            </a>
            ,{" "}
            <a
              href="https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Images/Using_CSS_gradients"
              target="blank"
            >
              Mozilla
            </a>{" "}
            <a
              href="https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient"
              target="blank"
            >
              Developer
            </a>{" "}
            <a
              href="https://developer.mozilla.org/en-US/docs/Web/CSS/radial-gradient"
              target="blank"
            >
              Network
            </a>
            ,{" "}
            <a
              href="https://www.w3.org/TR/css3-images/#gradients"
              target="blank"
            >
              W3C
            </a>
            ,{" "}
            <a
              href="http://www.quirksmode.org/css/images/gradients.html"
              target="blank"
            >
              QuirksMode
            </a>
            . Compatibility Data from{" "}
            <a href="https://caniuse.com/#feat=css-gradients" target="blank">
              Can I Use
            </a>
            . More information about compatibility on{" "}
            <a
              href="http://www.quirksmode.org/css/images/gradients_desktop.html"
              target="blank"
            >
              Desktop
            </a>{" "}
            and{" "}
            <a
              href="http://www.quirksmode.org/css/images/gradients_mobile.html"
              target="blank"
            >
              Network
            </a>
            .
          </div>
        </section>
      </div>
    </div>
  );
}
